// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRDBgNuQKaQdMizLssVlB5JkxO0_VdS3Q',
    appId: '1:905791191293:web:c6bd3f130292129203e694',
    messagingSenderId: '905791191293',
    projectId: 'car-rescue1',
    authDomain: 'car-rescue1.firebaseapp.com',
    storageBucket: 'car-rescue1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc-IfxknRLzRjJ3t9KyH8Je51XnHCV0rk',
    appId: '1:905791191293:android:e480a5565097061f03e694',
    messagingSenderId: '905791191293',
    projectId: 'car-rescue1',
    storageBucket: 'car-rescue1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxeJ4PYaydoJuipEyE3p-63gQkC2XC_do',
    appId: '1:905791191293:ios:6945ef4952326ca803e694',
    messagingSenderId: '905791191293',
    projectId: 'car-rescue1',
    storageBucket: 'car-rescue1.appspot.com',
    iosBundleId: 'com.example.carApp',
  );
}
